
//
//ZERO-DETECTION PIN - EXTI RISE/FALL
//
#define ZERO_DETECT_PORT GPIOD
#define ZERO_DETECT_PIN GPIO_PIN_3
//#define ZERO_DETECT_EXTI EXTI_PORT_GPIOD
#define ZERO_DETECT_EXTI_RISE_FALL 0b11000000	//zero-detect-port exti sensitivity (write to CR1)


//
//SWITCH PIN - INPUT
//
#define SWITCH_PORT GPIOC
#define SWITCH_PIN GPIO_PIN_6
//#define SWITCH_EXTI_RISE_FALL 0b00110000	//switch-port exti sensitivity (write to CR1)


//
//LED-PANEL - PUSH-PULL
//
#define LED_GPIO_PORT GPIOC
#define LED_GPIO_PINS GPIO_PIN_3 | GPIO_PIN_4 | GPIO_PIN_5
#define LED_GPIO_MASK  0b11000111

#define LEDS_OFF LED_GPIO_PORT->ODR &= LED_GPIO_MASK;
#define LEDS_SET(val) LED_GPIO_PORT->ODR &= LED_GPIO_MASK; LED_GPIO_PORT->ODR ^= (val<<3);



//
//HEATER - PUSH-PULL
//
#define HEATER_PORT GPIOD
#define HEATER_PIN GPIO_PIN_4

#define HEATER_ON HEATER_PORT->ODR &= ~HEATER_PIN
#define HEATER_OFF HEATER_PORT->ODR |= HEATER_PIN


//
//TEMP SENSOR - ADC
//
#define TEMP_SENS_ADC_CHANNEL ADC1_CHANNEL_3




void GPIO_Config(void);

extern INTERRUPT_HANDLER(EXTI_PORTA_IRQHandler, 3);
extern INTERRUPT_HANDLER(EXTI_PORTB_IRQHandler, 4);
extern INTERRUPT_HANDLER(EXTI_PORTC_IRQHandler, 5);
extern INTERRUPT_HANDLER(EXTI_PORTD_IRQHandler, 6);
