#define ZERO_DETECT_PORT GPIOA
#define ZERO_DETECT_PIN GPIO_PIN_3
#define ZERO_DETECT_EXTI EXTI_PORT_GPIOA

#define LED_GPIO_PORT GPIOC
#define LED_GPIO_PINS GPIO_PIN_3 | GPIO_PIN_4 | GPIO_PIN_5
#define LED_GPIO_MASK  0b11000111

#define STATUS_LED_PORT GPIOD
#define STATUS_LED_PIN GPIO_PIN_3

#define STATUS_LED_ON STATUS_LED_PORT->ODR |= STATUS_LED_PIN
#define STATUS_LED_OFF STATUS_LED_PORT->ODR &= ~STATUS_LED_PIN
#define STATUS_LED_REV STATUS_LED_PORT->ODR ^= STATUS_LED_PIN

void GPIO_Config(void);

extern INTERRUPT_HANDLER(EXTI_PORTA_IRQHandler, 3);

